services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    volumes:
      - comai_funds_flow_db:/data
      - comai_funds_flow_logs:/logs

volumes:
  comai_funds_flow_db:
    name: comai_funds_flow_db
  comai_funds_flow_logs:
    name: comai_funds_flow_logs