services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    volumes:
      - comai-ff-db:/data
      - comai-ff-logs:/logs

volumes:
  comai-ff-db:
    name: comai-ff-db
  comai-ff-logs:
    name: comai-ff-logs